### DISCUSSION TITLE
Icon Helper

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [Mariusthvdb/custom-icons#16] [General]
on the icon helper: In my setup, the icons are not filled out, nor does the html code in Dillinger show anything but the link

<img width="2143" alt="Schermafbeelding 2022-05-14 om 14 14 49" src="https://user-images.githubusercontent.com/33354141/168425300-647105af-b72e-4c77-8e55-e276548b0020.png">
<img width="683" alt="Schermafbeelding 2022-05-14 om 14 15 01" src="https://user-images.githubusercontent.com/33354141/168425303-9529452b-f936-42db-8c9e-8d932c6eb91a.png">

I take it thats because I am editing it locally, and within the repo?
or am I not doing things as they are supposed to....

the `repo does show correctly:

<img width="435" alt="Schermafbeelding 2022-05-14 om 14 18 07" src="https://user-images.githubusercontent.com/33354141/168425356-fe8d7fa9-2c4b-4b7d-94dd-f94016a44d93.png">

**Comment by arallsopp** [comment]
Dillinger is using strict markdown, whereas GitHub lets you use image tags. Unfortunately, there’s not really any other solution in native markdown that lets you specify a size for an image. 

If your images are all the same size now as part of your workflow, I can just back this out and make it use markdown as before. 

Do you have a development environment, btw? I mean, can you host web files on your local host? Or run a php script?

**Reply by Mariusthvdb** [reply]
guess I should look at that again yes, had it before, but never got the hang of it. any specific needs for this I should take into consideration?

btw, did you check the images now, Isnt that much better to view?

also, some of the custom icons are a bit off, compared to the mdi material standards and guidelines. I guess we should try to keep up that as much as possible.

**Reply by Mariusthvdb** [reply]
just discovered when previewing as pdf , it does show all the icons correctly:
https://dillinger.io/factory/fetch_pdf

**Reply by arallsopp** [reply]
You can now choose to generate the table as pure markdown (with native image sizing) or with icons as image tags, which specify 24px. 
<img width="517" alt="image" src="https://user-images.githubusercontent.com/2462104/168480846-23bc036a-e0d8-44d7-b5ae-9409bdc00663.png">

**Comment by Mariusthvdb** [comment]
btw, this is a quick and dirty way to test the icons the library. Havent given it a thought for a decluttering, out auto-entities yet. Maybe thats not possible. Anyways, would be cool if the icon helper could also blurb this? Thinking about adding a tooltip with the icon name:

```
    - type: grid
      columns: 6
      cards:
        - type: custom:button-card
          icon: cil:apple-homepod
        - type: custom:button-card
          icon: cil:apple-homepod-mini
        - type: custom:button-card
          icon: cil:cellphone-iphone
        - type: custom:button-card
          icon: cil:laptop-mac
        - type: custom:button-card
          icon: cil:desklamp-on
        - type: custom:button-card
          icon: cil:delete-alert
        - type: custom:button-card
          icon: cil:delete-alert-outline
        - type: custom:button-card
          icon: cil:dishwasher-silverware
        - type: custom:button-card
          icon: cil:earth-alert
        - type: custom:button-card
          icon: cil:earth-vibrate
        - type: custom:button-card
          icon: cil:home-broken
        - type: custom:button-card
          icon: cil:home-broken-outline
        - type: custom:button-card
          icon: cil:home-export-no-roof-outline
        - type: custom:button-card
          icon: cil:home-import-no-roof-outline
        - type: custom:button-card
          icon: cil:home-climate
        - type: custom:button-card
          icon: cil:home-climate-outline
        - type: custom:button-card
          icon: cil:home-pulse
        - type: custom:button-card
          icon: cil:light-switch
        - type: custom:button-card
          icon: cil:shutter-0
        - type: custom:button-card
          icon: cil:shutter-1
        - type: custom:button-card
          icon: cil:shutter-2
        - type: custom:button-card
          icon: cil:shutter-3
        - type: custom:button-card
          icon: cil:shutter-4
        - type: custom:button-card
          icon: cil:ikea-death-star
        - type: custom:button-card
          icon: cil:table-cylinder-lamp
        - type: custom:button-card
          icon: cil:uplighter
        - type: custom:button-card
          icon: cil:uplighter-2-way
        - type: custom:button-card
          icon: cil:sun-angle
        - type: custom:button-card
          icon: cil:sun-angle-variant
        - type: custom:button-card
          icon: cil:thermometer-empty
        - type: custom:button-card
          icon: cil:thermometer-full
```

<img width="474" alt="Schermafbeelding 2022-05-14 om 17 59 57" src="https://user-images.githubusercontent.com/33354141/168439550-93422285-19d4-4dd4-a353-7e22b8873449.png">

bare bones tooltip:
<img width="169" alt="Schermafbeelding 2022-05-14 om 18 01 44" src="https://user-images.githubusercontent.com/33354141/168439625-4c4b55cc-e1b6-4abc-8adb-9d516446f270.png">
